### ISSUE TITLE
Readme example doesn't run

### ISSUE THREAD

**Issue by j4m3s** [PhpGt/Database#11]
```Gt\Database\DatabaseClient::__construct() must be an instance of Gt\Database\Query\QueryCollectionFactory, instance of Gt\Database\Connection\Settings given```

The ability to specify a `QueryCollectionFactory` is great so I can use a different folder for queries (`src/sql/query` is my personal preference so I can have migrations in `src/sql/migrations`).

On which note, looking at the source, am I right in thinking that the default base directory for query files is actually `getcwd()` rather than `src/query` as specified in the readme example?

**Comment by g105b** [comment]
Will be handled by #21.
