### ISSUE TITLE
Is it possible to set options for PDO?

### ISSUE THREAD

**Issue by j4m3s** [PhpGt/Database#13]
I frequently re-use named parameter markers to optimise or avoid the need for subqueries.  According to the [PHP manual](http://php.net/manual/en/pdo.prepare.php):
>You cannot use a named parameter marker of the same name more than once in a prepared statement, unless emulation mode is on

The necessary parameter is `PDO::ATTR_EMULATE_PREPARES => true`

By default it is turned-off in Illuminate database, meaning re-use of parameter markers throws an `SQLSTATE[HY093]: Invalid parameter number` error.

This does highlight the need to allow configuration of PDO parameters via PhpGt/Database, and possibly also to set this particular parameter to "on" by default.

To configure database parameters in Illuminate database, you add an `options` key to the associative array of parameters used in `Manager->addConnection()`, as follows:
```php
use Illuminate\Database\Capsule\Manager as Capsule;

$capsule = new Capsule;
$capsule->addConnection([
    'driver' => 'mysql',
    'host' => $db_host,
    'database' => $db_name,
    'username' => $db_username,
    'password' => $db_password,
    'charset' => 'utf8',
    'collation' => 'utf8_unicode_ci',
    'prefix' => '',
    'options' => [
        PDO::ATTR_EMULATE_PREPARES => true,
    ]
]);
```

**Comment by g105b** [comment]
I've just been wondering this myself. Please see 1fc8544.
