### ISSUE TITLE
Persistent connections?

### ISSUE THREAD

**Issue by g105b** [PhpGt/Database#15]
Read through the pros/cons here: http://stackoverflow.com/questions/23432948/fully-understanding-pdo-attr-persistent

**Comment by j4m3s** [comment]
Is this not solved by #13? The user can specify the option if they want it.

**Comment by g105b** [comment]
Yes it is, I'm just wondering if this should be on by default, or where possible. I haven't ever used the functionality so haven't looked into the implications.

**Comment by j4m3s** [comment]
Might best to leave it manual for now, use it for a few months and review again
