### ISSUE TITLE
Any tests for the db-migrate script?

### ISSUE THREAD

**Issue by j4m3s** [PhpGt/Database#22]
was just poking around and it looks like there could be some logic errors in the autoload section of the script.  For example I could specify an autoload path but it would be modified (at least prefixed with ../) if I haven't specified the repoBasePath?  

(and it's a single 153 line function - uncle Bob wouldn't approve :) )

**Comment by g105b** [comment]
Indeed he wouldn't - but I see a lot of value in getting something working quick and dirty before generalising the script ready for prod.

**Comment by j4m3s** [comment]
Agree!  So the db-migrate functionality is not production-ready yet?

**Comment by g105b** [comment]
There have only been pre-releases so far, no production ready releases https://github.com/PhpGt/Database/releases

**Comment by g105b** [comment]
@j4m3s please take a look at the script and Migrator class, would like to hear your opinion. It's currently not unit tested, so that needs to be done before the v1 release is made.

**Comment by j4m3s** [comment]
If I were to be super-critical I'd say the db-migrate script should be nothing more than calling a 'go' method on one or more other classes.  

For example, the functionality embedded in the script at the moment that looks for the autoload file can't be tested in isolation.  
The same with the argv parsing (there must be a library for that already, the equivalent of GNU `getopt` that wouldn't hard-code it into the first parameter position and would cope with users specifying --force=false).  

I'm loving the rest of it though - the script calls the existing Settings, Config and Migrator objects which is just the way it should be.  I'd be tempted to add a method to "set" each of those objects to help with mocking them out in the unit tests.  (same for dbClient on the Migrator class?)

Specifically on the Migrator class I've taken to using a HEREDOC for query strings rather than imploding arrays.  That way you can specify the dialect using an /** @lang MySQL */ comment and the syntax can be checked (or even run) by an IDE or scrutinizer etc.  The implode call shouldn't be there IMHO - it serves no functional purpose and makes the code harder to read.

Also in Migrator, could the `getMigrationCount` method be renamed to `getCurrentMigrationCount`?  I expected the method to return the number of migrations in the directory - or maybe the number of migrations to be executed.  

Uncle-Bob style, should the Exception handling when the version table doesn't exist be a separate method?  

Lastly - a dumb question - should error messages be echo'ed the same way as success messages?  Or use error_log or something to flag them as errors (like directing them to stderr or prepending each line with asterisks, using ANSI colours or something)?  That in itself suggests you might want to use `message()` and `errorMessage()` function each time to write out rather than directly hitting echo.  Then you could always add functionality to check if a user has a logging framework installed or include one yourself if you decide it's worth it later-on.

(Putting this as a long freeform comment didn't feel right but I couldn't think of a better way to do it outside a morass of pull requests).

**Comment by g105b** [comment]
Current db-migrate script creates the dependencies and passes them to the migrator. This is the job for MigratorFactory.
