### ISSUE TITLE
Separate migrations and view creations?

### ISSUE THREAD

**Issue by g105b** [PhpGt/Database#24]
It is useful to refer back to views in source code, but if they are in amongst the migrations they may be difficult to find.

Also, a future migration is likely to break a view.

Run all view creation scripts after migrations have occurred somehow? @j4m3s what do you think about this?

**Comment by j4m3s** [comment]
The DB IDE (or SQL command line) will show the latest version of a view.  Do you mean in the scenario where you want to update a view (which involves deleting and recreating it)?  In that case I don't think it would make much difference to separate the two.  You'll still have to grep all of the files in the directory to look for the last file that drops & recreates the view.  I don't think it would any harder to do that in the migrations directory than in a separate Views directory.

Your last question is a real killer for the idea of separating the two actually - you have to interleave them somehow as the view will relate to the tables as they are at the point when they're defined.
