### ISSUE TITLE
Binding non-column values in prepared statements 

### ISSUE THREAD

**Issue by g105b** [phpgt/database#4]
The way PDO protects against SQL injection is by asking the database driver for the **expected variable type** of placeholders. This is done by checking the schema against where the placeholders exist. 

When PDO sees a placeholder that isn't bound to a column of specific type, for example: `limit :limit`, it either chooses to bind `NULL` or `0`, as it doesn't know what to do with the provided value.

Version 2 solved this by checking for predefined strings, such as `:limit`, and using `str_replace` on those parameters. But is there a better solution?

**Comment by j4m3s** [comment]
Is this caused by this pdo bug?: https://bugs.php.net/bug.php?id=44639

If so, would turning off PDO::ATTR_EMULATE_PREPARES help?  

If not, maybe the best approach would be to add optional methods to your query->execute called ->withLimit(x) and ->skipping(y)

**Comment by j4m3s** [comment]
Also.  Am I right saying that limit and skip are non-ansi mysql specific extensions?  if so this is the perfect situation for OO, with those two fluent-interface methods only available on a mysql query object - a subclass of the main sql query class.

**Comment by g105b** [comment]
Solved for now, removing non-used keys is the answer. I assume that the planned database wrapper (#5) will handle this automatically.
