### ISSUE TITLE
Should baseDirectory for Migrator actually be the migration directory?

### ISSUE THREAD

**Issue by j4m3s** [PhpGt/Database#40]
The first parameter for Settings is the base directory - which in the normal QueryCollection context is the parent dir for all query collections.  

In the Migrator, this directory is not used as it isn't relevant.  It doesn't use query collections (although it is built-up by the db-migrate script for some reason?).

What **is** relevant for Migrator is the migration path - but that is passed-in as a separate variable to the Migrator constructor.

So... should the baseDirectory in the Settings object actually be set to the migration path for Migrator, removing the need for a separate migrationPath?  Or should there be two separate Settings subclasses - one that's relevant for QueryCollections and one that's relevant for Migrator?

The question is born from the possibility (or fact in my case) of the migrations being stored outside the query directory, rather than as a subdir of it.

**Comment by j4m3s** [comment]
I think I can see why the baseDirectory has made its way into Settings - is it because it's stored in the Driver?  If so, may I challenge whether that's really the right place for it?  The Driver doesn't need to know about/ hold/ store the QueryCollection's baseDirectory does it?

**Comment by g105b** [comment]
The Migrator class is constructed with a $path parameter, which is now the absolute path to the migration directory. The base path, which is stored in the Settings object, refers to the containing "Query" directory, which is the root containing directory for all SQL files and query collection directories.
