### ISSUE TITLE
Migrations using timestamps

### ISSUE THREAD

**Issue by g105b** [PhpGt/Database#7]
Opportunity for another gt command: migrate.

Migration filenames should use a sequence that **can't clash when multiple developers are working concurrently** (don't use incremental numbers, for example).

Use the unix timestamp, suffixed with either a description of the migration _or_ a random hash.

**IMPORTANT - don't trust the number in the sequence that has been migrated to** - two or more developers could have checked out from the same point of migration. Developer A runs their migration of 10 scripts, then developer B's migration number will be less than the current state of the migration.

The migration table **must** make a record for every script that has been run, by name. The migration script must check each and every script from first to last, running missing scripts in order.

How should we handle if developer B's migrations have side effects to developer A's, or if the side effects of each developer's migrations cause the other's to fail? Manual intervention involving a future fix migration?

**Comment by j4m3s** [comment]
Sequential numbers are important, and a version number clash **should be fatal**.  It indicates that two developers have committed without knowing the other is doing something concurrently.  That means neither has coded to a known state of the database.  

Adding a timestamp doesn't help I don't think - they would still be deploying potentially inconsistent code.

Whoever deploys first wins.  Anyone deploying after that but trying to re-use a same (or lower) version number should fail, it's the only safe thing to do.

**Comment by g105b** [comment]
Agreed. What am I thinking?
